/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jianqiang_jnihelloworld_AnotherJniUtils */

#ifndef _Included_com_jianqiang_jnihelloworld_AnotherJniUtils
#define _Included_com_jianqiang_jnihelloworld_AnotherJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jianqiang_jnihelloworld_AnotherJniUtils
 * Method:    sayGoodBye
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jianqiang_jnihelloworld_AnotherJniUtils_sayGoodBye
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
